In [13]:
import torch
import torch.nn as nn
from kasim_model import Kasim_Model
from kasim_tokenizer import Tokenizer   

k_tokenizer=Tokenizer("tokenizer.json")
sentence = "the capital of united states and the capital of france"
tokens = k_tokenizer.encode(sentence)
tokens = torch.tensor(tokens).unsqueeze(0)  # Add batch dimension




C:\Users\kasim\AppData\Local\Temp\ipykernel_9488\2483573362.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokens = torch.tensor(tokens).unsqueeze(0)  # Add batch dimension


In [14]:
import torch
from kasim_model import Kasim_Model
torch.manual_seed(42)
k_model = Kasim_Model(vocab_size=50257, embed_dim=512, context_length=64, num_heads=8, num_layers=6)
sentence_meanings= k_model(tokens)
sentence_meanings

tensor([[[ 0.5773,  0.2154,  0.5246,  ...,  0.1469,  0.0349, -0.8509],
         [ 0.3441, -0.0503,  0.3869,  ..., -0.5260, -0.1955,  0.2970],
         [-0.0698, -1.2000,  0.7695,  ...,  0.3392, -1.2433,  0.2541],
         ...,
         [ 0.2233, -0.9883, -1.0801,  ..., -0.3009,  0.7344,  0.2795],
         [ 0.7321,  0.0971, -0.0744,  ...,  1.1271, -0.2298,  0.9680],
         [ 0.0103,  0.0353,  0.3010,  ...,  0.4795,  0.2186, -0.2663]]],
       grad_fn=<ViewBackward0>)

In [15]:
k_model 

Kasim_Model(
  (embedding): Embedding(50257, 512)
  (pos_embed): Embedding(64, 512)
  (layers): Sequential(
    (0): KasimDecoderBlock(
      (self_attention): Kasim_Multi_Head_Attention(
        (multi_head_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
        )
        (projection): Linear(in_features=512, out_features=512, bias=True)
      )
      (norm1): KasimRMSNorm()
      (mlp): KasimMLP(
        (gate_proj): Linear(in_features=512, out_features=2048, bias=True)
        (up_proj): Linear(in_features=512, out_features=2048, bias=True)
        (down_proj): Linear(in_features=2048, out_features=512, bias=True)
        (gelu): KasimGelu()
      )
      (norm2): KasimRMSNorm()
    )
    (1): KasimDecoderBlock(
      (self_attention): Kasim_Multi_Head_Attention(
        (multi_head_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512

In [16]:
import torch

tahmin=torch.softmax(sentence_meanings[0],dim=-1)

In [17]:
import torch 
max_prob,max_index =torch.max(tahmin,dim=-1)
max_prob,max_index,tahmin

(tensor([0.0002, 0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0002, 0.0002, 0.0005,
         0.0002, 0.0002, 0.0002, 0.0002, 0.0002, 0.0003, 0.0002, 0.0002, 0.0002,
         0.0002, 0.0002], grad_fn=<MaxBackward0>),
 tensor([ 7612,  1521,  1850, 16444, 48746, 27303, 15568, 35671,   413, 45854,
         44295,  1081, 17252, 25793, 10319, 16030,  1818, 29364, 35223, 34126]),
 tensor([[2.6860e-05, 1.8705e-05, 2.5481e-05,  ..., 1.7466e-05, 1.5615e-05,
          6.4394e-06],
         [2.2012e-05, 1.4837e-05, 2.2974e-05,  ..., 9.2212e-06, 1.2832e-05,
          2.0998e-05],
         [1.4586e-05, 4.7105e-06, 3.3761e-05,  ..., 2.1955e-05, 4.5109e-06,
          2.0165e-05],
         ...,
         [2.0670e-05, 6.1542e-06, 5.6144e-06,  ..., 1.2237e-05, 3.4459e-05,
          2.1864e-05],
         [3.3645e-05, 1.7829e-05, 1.5019e-05,  ..., 4.9938e-05, 1.2858e-05,
          4.2595e-05],
         [1.6628e-05, 1.7049e-05, 2.2237e-05,  ..., 2.6584e-05, 2.0479e-05,
          1.2609e-05]], grad_fn=<SoftmaxBa